spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "**********@gmail.com"
    password: "***********"
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.ssl.trust: smtp.gmail.com
  datasource:
    url: "jdbc:postgresql://localhost:5432/email?createDatabaseIfNotExist=true&useSSL=false"
    username: postgres
    password: root
  jpa:
    show-sql: true
    database: POSTGRESQL
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect,